name: games-ci

on:
  push:
    paths:
      - "games-svc/src/**"
      - "games-svc/test/**"
      - ".github/workflows/games-ci.yml"
  pull_request:
    paths:
      - "games-svc/src/**"
      - "games-svc/test/**"
      - ".github/workflows/games-ci.yml"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Cache NuGet
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      # Build da API (opcional, mas útil pra garantir que a lib compila)
      - name: Restore (API)
        working-directory: games-svc/src/games-svc
        run: dotnet restore

      - name: Build (Release, API)
        working-directory: games-svc/src/games-svc
        run: dotnet build --configuration Release --no-restore

      # Tests: rodar de dentro da pasta de testes para evitar caminho absoluto no vstest
      - name: Restore (Tests)
        working-directory: games-svc/test/games-svc.Tests
        run: dotnet restore

      - name: Build (Release, Tests)
        working-directory: games-svc/test/games-svc.Tests
        run: dotnet build --configuration Release --no-restore

      - name: Test (Release)
        working-directory: games-svc/test/games-svc.Tests
        run: dotnet test --configuration Release --no-build --collect:"XPlat Code Coverage" --logger "trx;LogFileName=test_results.trx"

      - name: Upload Test Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: games-tests-artifacts
          path: |
            games-svc/test/games-svc.Tests/TestResults/*.trx
            games-svc/test/games-svc.Tests/TestResults/**/coverage.cobertura.xml
            games-svc/test/games-svc.Tests/TestResults/**/coverage.info
